### ISSUE TITLE
2024-05-25 release of MESA not fully installable and prevents WINE games from launching.

### ISSUE THREAD

**Issue by darinsmiller** [ernstp/ppa-mesarc#21] opened 2024-05-25 19:29 UTC
Unable to find issue on bug tracker: https://gitlab.freedesktop.org/mesa/mesa/-/issues

**Issue with the PPA**
The following packages have unmet dependencies:
 libgl1-mesa-dri:i386 : Depends: libllvm18:i386 but it is not installed
 libosmesa6:i386 : Depends: libllvm18:i386 but it is not installed
 mesa-va-drivers:i386 : Depends: libllvm18:i386 but it is not installed
 mesa-vdpau-drivers:i386 : Depends: libllvm18:i386 but it is not installed
 mesa-vulkan-drivers:i386 : Depends: libllvm18:i386 but it is not installed

sudo apt install -f failed to resolve.

**Comment by darinsmiller** [comment] 2024-05-25 19:30
Forgot to include system info:

Operating System: Ubuntu 12
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.8.0-31-generic (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: AMD Radeon RX 6750 XT
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X570S AORUS ELITE AX
System Version: -CF

**Comment by oyvindln** [comment] 2024-05-26 17:18
I think the problem is this - the i386 architecture version of the libllvm18 package which is a dependency of the latest mesa package version in this repo is broken at the moment:
https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-18/+bug/2063207

There is a [hacky](https://www.reddit.com/r/linux_gaming/comments/1cgzdma/workaround_libllvm18i386_install_issue_on_ubuntu/) workaround you can to solve it manually but it's not really ideal.

Not sure if it's doable to downgrade the dependency to llvm 17 until that bug is sorted maybe or if it needs llvm18 and we just have to wait - not sure if it's also an issue with oibaf's ppa or not.

I was going to comment this in the previous issue as this is what caused it to break on my system after the failing builds were fixed but might as well note it here.

**Comment by oyvindln** [comment] 2024-05-27 17:20
According to the comment in the launchpad issue, oibaf changed to using llvm 17 for building mesa for their mesa git ppa in the meantime so it does seem like that is doable - anyway looks like ubuntu/debian people are looking into it so hopefully it'll be sorted eventually.

**Comment by ernstp** [comment] 2024-05-27 23:33
Should be fixed now

**Closed by ernstp** 2024-05-27 23:33 UTC
