### ISSUE TITLE
22.2.2+git2210261923.159bc5b3ded~k~mesarc1 is causing font and graphical glitches

### ISSUE THREAD

**Issue by YamiYukiSenpai** [ernstp/ppa-mesarc#13] opened 2022-11-20 21:05 UTC
My system is on Ryzen 9-5900X & RX 6900XT

I had to downgrade to 22.2.2+git2210261923.159bc5b3ded~k~mesarc1 to fix the glitches.

These are the ones I downgraded:

```
libegl-mesa0/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 amd64 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
libegl-mesa0/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 i386 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
libgbm1/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 amd64 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
libgbm1/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 i386 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
libgl1-mesa-dri/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 amd64 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
libgl1-mesa-dri/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 i386 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
libglapi-mesa/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 amd64 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
libglapi-mesa/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 i386 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
libglx-mesa0/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 amd64 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
libglx-mesa0/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 i386 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
libosmesa6/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 amd64 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
libosmesa6/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 i386 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
libxatracker2/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 amd64 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
mesa-va-drivers/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 amd64 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
mesa-va-drivers/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 i386 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
mesa-vdpau-drivers/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 amd64 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
mesa-vulkan-drivers/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 amd64 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
mesa-vulkan-drivers/kinetic 22.3.0~rc3+git2211171818.76e3938fec4~k~mesarc3 i386 [upgradable from: 22.2.2+git2210261923.159bc5b3ded~k~mesarc1]
```

Figure I should point it out

**Comment by ernstp** [comment] 2022-11-21 14:26
Upstream issue, already reported there: https://gitlab.freedesktop.org/mesa/mesa/-/issues/7743
Seems to be fixed on master but don't know which commit yet.

**Comment by ernstp** [comment] 2022-11-22 00:01
Hmm, looks more and more like a build/config specific issue to my ppa only!

**Comment by YamiYukiSenpai** [comment] 2022-11-22 11:40
Just updated, and it's good now :-)

What was the issue, if I  may ask?

**Comment by ernstp** [comment] 2022-11-22 12:02
Seems to be a very random issue caused by Link Time Optimization. You can read more details in the mesa issue I linked.

**Closed by ernstp** 2022-11-22 12:02 UTC
